// AUTO-GENERATED: additional code-based attractions (beyond planner_places). Do not edit by hand.
import type { PlannerPlace } from '@/lib/validation/planner';

export const ADDITIONAL_ATTRACTIONS_RAW: PlannerPlace[] = [
  {
    id: 'mont-choisy-beach',
    name: 'Mont Choisy Beach',
    category: 'Beach',
    region: 'North',
    lat: -20.0114,
    lng: 57.5347,
    durationMin: 150,
    closesAt: null,
    blurb:
      'One of the longest public beaches in northern Mauritius, Mont Choisy stretches in a wide crescent of white sand between Trou aux Biches and Grand Baie. Calm, shallow lagoon waters make it good for swimming, and a shady fringe of filao trees backs the shore. Popular with families and locals for picnics, kitesurfing and weekend gatherings.',
    imageUrl: null,
  },
  {
    id: 'bain-boeuf-beach',
    name: 'Bain Boeuf Beach',
    category: 'Beach',
    region: 'North',
    lat: -19.9889,
    lng: 57.6122,
    durationMin: 120,
    closesAt: null,
    blurb:
      "A public beach near Grand Baie on Mauritius' north coast, fronting a shallow turquoise lagoon protected by a reef. Coin de Mire (Gunner's Quoin) island stands offshore, framing the view. Casuarina trees give shade, and the calm, gently sloping water suits families and swimming. It is quieter than nearby Grand Baie, with snorkelling spots and food stalls close by.",
    imageUrl: null,
  },
  {
    id: 'pointe-aux-piments',
    name: 'Pointe aux Piments',
    category: 'Beach',
    region: 'North',
    lat: -20.0667,
    lng: 57.5236,
    durationMin: 120,
    closesAt: null,
    blurb:
      'Pointe aux Piments is a quiet coastal village on the northwest shore between Balaclava and Trou aux Biches. Its public beach offers calm, shallow lagoon water sheltered by the reef, with rocky stretches alongside sandy patches. Popular for snorkelling, swimming and shore diving, it is less crowded than nearby Trou aux Biches and sits near the Mauritius Aquarium.',
    imageUrl: null,
  },
  {
    id: 'anse-la-raie',
    name: 'Anse la Raie',
    category: 'Beach',
    region: 'North',
    lat: -19.9889,
    lng: 57.6447,
    durationMin: 120,
    closesAt: null,
    blurb:
      "A quiet public beach on Mauritius's far north coast, between Cap Malheureux and Grand Gaube. Its shallow lagoon and steady cross-shore winds make it a well-known spot for kitesurfing and windsurfing. Filao trees line the shore for shade, and the calm water suits swimming. From here you can see the northern offshore islands.",
    imageUrl: null,
  },
  {
    id: 'chateau-de-labourdonnais',
    name: 'Château de Labourdonnais',
    category: 'Culture',
    region: 'North',
    lat: -20.0876,
    lng: 57.6486,
    durationMin: 120,
    closesAt: '17:00',
    blurb:
      'A restored 19th-century colonial mansion near Mapou, built in 1859 and furnished in period style. Visitors tour the house, stroll the surrounding orchards and gardens of fruit trees and palms, and sample products from the on-site rum distillery. Tastings of rums, fruit juices and jams are available, with a restaurant set among the grounds.',
    imageUrl: null,
  },
  {
    id: 'laventure-du-sucre',
    name: "L'Aventure du Sucre",
    category: 'Culture',
    region: 'North',
    lat: -20.1033,
    lng: 57.5806,
    durationMin: 120,
    closesAt: '17:00',
    blurb:
      "Housed in the restored Beau Plan sugar factory near Pamplemousses, this museum traces Mauritius's sugar industry and its links to slavery, indenture and rum. Original machinery and interactive displays explain cane processing, and the visit ends with a tasting of unrefined sugars and local rums. A self-guided route suits families and history-minded travellers alike.",
    imageUrl: null,
  },
  {
    id: 'grand-bassin-ganga-talao',
    name: 'Grand Bassin (Ganga Talao)',
    category: 'Culture',
    region: 'Central',
    lat: -20.4181,
    lng: 57.4922,
    durationMin: 75,
    closesAt: null,
    blurb:
      'A sacred crater lake high in the southern uplands, regarded as one of the holiest Hindu sites outside India. Temples line the shore alongside towering statues of Shiva and Durga, and pilgrims gather here in vast numbers during Maha Shivaratri. Visit for the spiritual atmosphere, the lakeside shrines, and resident monkeys.',
    imageUrl: null,
  },
  {
    id: 'corps-de-garde-mountain',
    name: 'Corps de Garde Mountain',
    category: 'Viewpoint',
    region: 'Central',
    lat: -20.2667,
    lng: 57.4833,
    durationMin: 180,
    closesAt: null,
    blurb:
      'Corps de Garde is a distinctive mountain rising above Quatre Bornes in central Mauritius, reaching roughly 720 metres. A well-trodden hiking trail climbs through rocky terrain to the summit ridge, rewarding walkers with sweeping views over the central plateau towns, the west coast and surrounding peaks. The route is steep in sections, so decent footwear and an early start are advised.',
    imageUrl: null,
  },
  {
    id: 'le-reduit',
    name: 'Réduit (Le Réduit)',
    category: 'Landmark',
    region: 'Central',
    lat: -20.2378,
    lng: 57.4983,
    durationMin: 45,
    closesAt: null,
    blurb:
      "Le Réduit is the State House, official residence of Mauritius's President, set on a wooded plateau in Moka. The colonial mansion dates to 1748, when the French built it as a refuge for settlers. Its formal gardens, century-old trees and ravine viewpoints open to the public only on occasional open days, so check before visiting.",
    imageUrl: null,
  },
  {
    id: 'gris-gris',
    name: 'Gris Gris',
    category: 'Viewpoint',
    region: 'South',
    lat: -20.4956,
    lng: 57.5269,
    durationMin: 45,
    closesAt: null,
    blurb:
      'Gris Gris is a rugged clifftop viewpoint near Souillac on Mauritius\'s southern coast, where there is no protective reef, so the open Indian Ocean crashes directly against the rocks. A short grassy headland trail leads past dramatic cliffs and the wave-battered "La Roche qui Pleure" formation. Bring sturdy shoes; swimming is dangerous due to strong surf.',
    imageUrl: null,
  },
  {
    id: 'bois-cheri-tea-plantation',
    name: 'Bois Chéri Tea Plantation',
    category: 'Food',
    region: 'South',
    lat: -20.4297,
    lng: 57.5283,
    durationMin: 120,
    closesAt: '17:00',
    blurb:
      "Mauritius's oldest and largest tea estate, set in the cool highlands of the Savanne district. A guided visit covers the working factory where leaves are dried, rolled and graded, plus a small museum tracing the island's tea history. It ends at a hilltop chalet overlooking Lake Bois Chéri, where you taste flavoured teas with views over the plantation.",
    imageUrl: null,
  },
  {
    id: 'domaine-de-saint-aubin',
    name: 'Domaine de Saint Aubin',
    category: 'Culture',
    region: 'South',
    lat: -20.4847,
    lng: 57.5469,
    durationMin: 120,
    closesAt: '17:00',
    blurb:
      "A historic 1819 sugar estate near Rivière des Anguilles, centred on a colonial mansion surrounded by sugarcane and tropical gardens. Visitors tour a small rum distillery producing agricultural rum from cane juice, plus vanilla and anthurium cultivation. The on-site restaurant serves Creole cuisine in the planter's house, making it a combined heritage, agriculture, and dining stop.",
    imageUrl: null,
  },
  {
    id: 'la-roche-qui-pleure',
    name: 'La Roche qui Pleure',
    category: 'Viewpoint',
    region: 'South',
    lat: -20.4972,
    lng: 57.5083,
    durationMin: 30,
    closesAt: null,
    blurb:
      'A rugged basalt headland near Le Souffleur on Mauritius\'s wild south coast, where waves break against dark cliffs. Its name, "the rock that cries," comes from a profile resembling a weeping face, an effect attributed to the writer Robert Edward Hart. Visitors come for dramatic sea views, crashing surf, and the windswept, undeveloped coastline.',
    imageUrl: null,
  },
  {
    id: 'blue-bay-marine-park',
    name: 'Blue Bay Marine Park',
    category: 'Beach',
    region: 'South',
    lat: -20.4442,
    lng: 57.7136,
    durationMin: 180,
    closesAt: null,
    blurb:
      "A protected marine park near Mahebourg on Mauritius's southeast coast, Blue Bay is known for its calm, shallow lagoon and one of the island's best-preserved coral reefs. Glass-bottom boat trips and snorkelling reveal living corals and reef fish. The white-sand public beach, shaded by trees, suits swimming and picnics in sheltered water.",
    imageUrl: null,
  },
  {
    id: 'mahebourg',
    name: 'Mahébourg',
    category: 'Landmark',
    region: 'South',
    lat: -20.4081,
    lng: 57.7,
    durationMin: 120,
    closesAt: null,
    blurb:
      "Mahébourg is a historic coastal town on Mauritius's southeast, founded in 1805 and named after governor Mahé de La Bourdonnais. Set on Grand Port bay near the 1810 naval battle site, it offers a lively Monday waterfront market, colonial architecture, the National History Museum, fishing boats, and views toward Île aux Aigrettes and the mountains.",
    imageUrl: null,
  },
  {
    id: 'mahebourg-naval-museum',
    name: 'Mahébourg Naval Museum',
    category: 'Culture',
    region: 'South',
    lat: -20.4081,
    lng: 57.7097,
    durationMin: 45,
    closesAt: '16:00',
    blurb:
      "Housed in the 18th-century Gheude colonial mansion in Mahébourg, this museum records the area's maritime past, including the 1810 Battle of Grand Port between French and British navies. Exhibits feature relics salvaged from shipwrecks like the Saint-Géran, old maps, cannons, bells, and period furniture, offering insight into Mauritius's colonial and naval history.",
    imageUrl: null,
  },
  {
    id: 'bel-ombre-nature-reserve',
    name: 'Bel Ombre Nature Reserve',
    category: 'Nature',
    region: 'South',
    lat: -20.4833,
    lng: 57.4,
    durationMin: 180,
    closesAt: '16:00',
    blurb:
      "A private nature reserve in the hills above Bel Ombre on Mauritius's south coast, covering native forest and former hunting estate land. Guided 4x4 safaris and hikes reach viewpoints over the lagoon, the Frederica waterfall and trails through endemic vegetation where deer, wild boar and monkeys roam. Booking ahead is required for the guided tours.",
    imageUrl: null,
  },
  {
    id: 'lion-mountain',
    name: 'Lion Mountain',
    category: 'Viewpoint',
    region: 'South',
    lat: -20.3753,
    lng: 57.7156,
    durationMin: 180,
    closesAt: null,
    blurb:
      'Lion Mountain rises above Vieux Grand Port on the southeast coast, its ridge resembling a resting lion. The free, unmarked hiking trail climbs through forest and over rock to the "head," rewarding climbers with sweeping views over Grand Port bay, Mahebourg and the offshore islands. The steep scramble near the top suits reasonably fit walkers.',
    imageUrl: null,
  },
  {
    id: 'roches-noires',
    name: 'Roches Noires',
    category: 'Beach',
    region: 'East',
    lat: -20.1083,
    lng: 57.7167,
    durationMin: 90,
    closesAt: null,
    blurb:
      "Roches Noires is a quiet public beach on Mauritius's northeast coast, named for the dark volcanic basalt rock lining its shore. A sheltered lagoon offers calm swimming, while the surrounding area is known for lava-tube caves formed by ancient flows. With few facilities and a local feel, it suits visitors seeking a relaxed alternative to busier resort beaches.",
    imageUrl: null,
  },
  {
    id: 'poste-lafayette',
    name: 'Poste Lafayette',
    category: 'Beach',
    region: 'East',
    lat: -20.1547,
    lng: 57.7556,
    durationMin: 90,
    closesAt: null,
    blurb:
      "Poste Lafayette is a quiet public beach on Mauritius's east coast, known for its rugged shoreline, scattered rocks and strong trade winds. The exposed conditions make it popular with kitesurfers and windsurfers rather than swimmers. Backed by casuarina trees and a few coastal hotels, it offers an unspoilt, less-crowded alternative to the island's busier resort beaches.",
    imageUrl: null,
  },
  {
    id: 'palmar-beach',
    name: 'Palmar Beach',
    category: 'Beach',
    region: 'East',
    lat: -20.2017,
    lng: 57.7639,
    durationMin: 120,
    closesAt: null,
    blurb:
      "Palmar Beach is a public stretch of white sand on Mauritius's east coast, near Belle Mare and Trou d'Eau Douce. A shallow turquoise lagoon protected by an offshore reef makes it calm for swimming, and casuarina trees behind the sand give natural shade. The east-facing shore is popular for sunrise views and quiet picnics.",
    imageUrl: null,
  },
  {
    id: 'domaine-de-letoile',
    name: "Domaine de l'Étoile",
    category: 'Nature',
    region: 'East',
    lat: -20.2783,
    lng: 57.6789,
    durationMin: 180,
    closesAt: '16:30',
    blurb:
      'A large private nature reserve in eastern Mauritius, covering roughly 2,000 hectares of valleys, rivers and forested hills. Visitors come for guided quad biking, buggy rides, horse riding, archery, hiking and ziplining across rugged terrain. The estate is also home to deer, wild boar and monkeys, and offers a restaurant with scenic views over the surrounding countryside.',
    imageUrl: null,
  },
  {
    id: 'tamarin-beach',
    name: 'Tamarin Beach',
    category: 'Beach',
    region: 'West',
    lat: -20.3258,
    lng: 57.3719,
    durationMin: 120,
    closesAt: null,
    blurb:
      "Tamarin Beach sits where the Rivière du Tamarin meets the sea on Mauritius's west coast. Unlike the island's lagoon beaches, it has open ocean rolling in, making it a well-known surf spot. The grey-gold sand, nearby salt pans and frequent dolphin sightings offshore draw both surfers and families. Sunsets here are a popular reason to linger.",
    imageUrl: null,
  },
  {
    id: 'la-preneuse-beach-martello-tower',
    name: 'La Preneuse Beach & Martello Tower',
    category: 'Culture',
    region: 'West',
    lat: -20.3678,
    lng: 57.3603,
    durationMin: 75,
    closesAt: '16:00',
    blurb:
      "A public beach on Mauritius's west coast beside a restored Martello Tower, one of several coastal forts the British built from local basalt in the 1830s. The tower houses a small museum on its defensive design, slavery, and colonial history, with views over Tamarin Bay. Combine the exhibit with a swim and picnic under the casuarina trees.",
    imageUrl: null,
  },
  {
    id: 'riviere-noire-black-river',
    name: 'Rivière Noire (Black River)',
    category: 'Landmark',
    region: 'West',
    lat: -20.3608,
    lng: 57.3672,
    durationMin: 90,
    closesAt: null,
    blurb:
      "Rivière Noire is a coastal village and district on Mauritius's west coast, named for the river that empties here. It is the island's deep-sea fishing hub, with charter boats heading out for marlin and tuna. The bay sits below the Black River Gorges and near Le Morne, making it a base for fishing trips, beaches, and inland excursions.",
    imageUrl: null,
  },
  {
    id: 'rhumerie-de-chamarel',
    name: 'Rhumerie de Chamarel',
    category: 'Food',
    region: 'West',
    lat: -20.4361,
    lng: 57.3897,
    durationMin: 90,
    closesAt: '17:00',
    blurb:
      "A working rum distillery set among sugarcane fields in the hills of Chamarel. Guided tours follow the process from cane crushing to fermentation, distillation, and ageing, ending with a tasting of agricultural rums and liqueurs. The on-site restaurant L'Alchimiste serves Mauritian dishes, making it a common stop alongside the nearby Seven Coloured Earths.",
    imageUrl: null,
  },
  {
    id: 'crystal-rock',
    name: 'Crystal Rock',
    category: 'Island',
    region: 'West',
    lat: -20.4419,
    lng: 57.3422,
    durationMin: 30,
    closesAt: null,
    blurb:
      'A jagged coral-rock formation rising alone from the shallow turquoise lagoon between Le Morne and Benitiers Island, off the southwest coast. Reached only by boat, it is a standard stop on catamaran and speedboat cruises, where visitors pause to photograph the rock against the bright water and swim in the surrounding shallows.',
    imageUrl: null,
  },
  {
    id: 'trois-mamelles',
    name: 'Trois Mamelles',
    category: 'Viewpoint',
    region: 'West',
    lat: -20.3667,
    lng: 57.4333,
    durationMin: 20,
    closesAt: null,
    blurb:
      'Trois Mamelles is a distinctive three-peaked mountain rising near the centre of western Mauritius, between Henrietta and the Black River Gorges area. Most visitors stop at roadside viewpoints to photograph its triple silhouette and the surrounding sugarcane plains. Experienced hikers tackle the ridge trail for sweeping coastal and highland panoramas, though the scrambling sections demand care and a head for heights.',
    imageUrl: null,
  },
  {
    id: 'albion-beach',
    name: 'Albion Beach',
    category: 'Beach',
    region: 'West',
    lat: -20.2167,
    lng: 57.4,
    durationMin: 90,
    closesAt: null,
    blurb:
      "A quiet public beach on Mauritius's west coast, fronted by a rocky shoreline and a small sandy stretch rather than a wide lagoon. It is best known for the nearby Albion Lighthouse, one of the island's few working lighthouses, perched on the cliffs above. Popular with local families and anglers, it offers calm sunset views and a low-key alternative to busier west-coast resorts.",
    imageUrl: null,
  },
  {
    id: 'tamarin-salt-pans-viewpoint',
    name: 'Tamarin Salt Pans Viewpoint',
    category: 'Viewpoint',
    region: 'West',
    lat: -20.3389,
    lng: 57.3756,
    durationMin: 30,
    closesAt: null,
    blurb:
      'A working coastal salt farm near Tamarin where seawater evaporates across a grid of shallow stone pans, leaving white salt harvested by hand. Roadside pullouts give views of the geometric basins set against the Black River mountains, especially photogenic in late afternoon light. A short, free stop for travellers passing along the west coast between Tamarin and Black River.',
    imageUrl: null,
  },
];
