// AUTO-GENERATED from data/belle-mare-tours-reviews.json (curated featured set). Do not edit by hand.
import type { ReviewStats, FeaturedReview } from './reviews';

export const REVIEW_STATS: ReviewStats = {
  total: 1076,
  average: 4.8,
  tripadvisor: {
    rating: 4.8,
    count: 959,
  },
  google: {
    rating: 4.7,
    count: 117,
  },
  histogram: {
    '1': 12,
    '2': 7,
    '3': 21,
    '4': 123,
    '5': 796,
  },
};

export const FEATURED_REVIEWS: FeaturedReview[] = [
  {
    id: '359271268',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Scooter Rental',
    text: 'Belle Mare Tours were very friendly. They were professional and efficient. Great price and reliable scooters. The only place I would rent a scooter from in the Belle Mare area. They will bring the scooter to your hotel and fetch it once you finished. Seeing mauritius by scooter is the only way :) :)',
    author: 'Anthea_dickson',
    authorLocation: null,
    date: '2016-03-28',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r359271268-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '643661909',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Superb excursion',
    text: 'We met Belinda on Belle Mar beach in front of our hotel.  Her proposition was the best and we have not been disappointed.\nCascades, Ile aux Aigrettes, Ile aux Cerf, wonderfully snorkeling, excellent " Café Mauricien " and superb barbecue on a secluded beach.\nHighly recommended.\nThanks Belinda for our best day in Mauritius',
    author: 'XavierC21',
    authorLocation: 'Lisbon, Portugal',
    date: '2019-01-04',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r643661909-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '400381656',
    source: 'TripAdvisor',
    rating: 5,
    title: 'june 2016 day trips',
    text: "We had read good reviews about this company on Trip advisor and so used them each time we went out from our hotel (Maritim) in Mauritius, of coarse the hotel preferred we had used their hotel taxis which were considerably more expensive and tried to stop outside companies coming up their drive. I don't like being told who I can and cannot use so we went with Belle Mare tours to go on a fabulous catamaran trip, also to Port Louis and to Flaq market etc. they were friendly drivers, punctual, helpful, clean vehicles, trustworthy and reasonably priced. What more could one ask for.",
    author: 'John H',
    authorLocation: 'Leamington Spa, United Kingdom',
    date: '2016-08-02',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r400381656-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '593861616',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great operator',
    text: 'Booked a driver for a day to visit  Boise Cherie tea plantation and Flacq market. Booking done via their office a short walk up the beach from Lux Belle Mare. No hard sell, and very helpful. Driver picked us up on time next day from hotel and was friendly, helpful and knowledgeable. Car was good, price was great',
    author: 'FTA',
    authorLocation: 'London, United Kingdom',
    date: '2018-07-07',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r593861616-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '550379955',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great day out',
    text: 'This is a must do trip such good fun swimming snorkelling site seeing a vary fast boat feeding monkeys excellent lunch on the beach the drivers are great at their job and of course all the while having a sip of vanilla rum. Absolute heaven',
    author: 'PJ M',
    authorLocation: 'Alicante, Spain',
    date: '2017-12-31',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r550379955-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '545318269',
    source: 'TripAdvisor',
    rating: 5,
    title: 'EXCELLENT RELIABLE SERVICE',
    text: 'We recently used Belle Mare Tours whilst in Mauritius.  I found their details from recommendations on Tripadvisor.  They were excellent in replying to emails, gave all information I requested, were reliable arriving on times stated and good value for money.  We used them to hire a scooter for the day, I enquired whether they would drop it off at hotel and for a nominal fee they did which was much more convenient.  As we were new to Mauritius I also asked their advice on where to go for an excursion not too far away.  They advised us of where they thought we would like and we booked a taxi to and from the place and had a great time. Definitely would use again.  Well done!!',
    author: 'amanda c',
    authorLocation: 'Dubai, United Arab Emirates',
    date: '2017-12-05',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r545318269-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '431435212',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Value for money!',
    text: 'Best tour operator, excellent service!\nGood drivers/guide, fluent in English and French, also German driver available.\nExotic shop is one of the best providing local products at affordable prices!',
    author: 'Zabeen C',
    authorLocation: null,
    date: '2016-10-25',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r431435212-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '408653274',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Very professional',
    text: 'What a find! We walked into Belle Mare and found Belle Mare tours, they are so friendly and so professional. They recommended local restaurants, the best place to exchange money etc. we rented a scooter from them and they delivered it to our hotel. We also booked a boat cruise through them which they had to postpone a couple of times because of the weather, they could have easily taken us on a windy/cloudy day but they rather postponed it and took us when the weather was great They are not there to just take your money, they want you to have a great time. All in all they made us feel so welcome. We will highly recommend them.',
    author: 'Heidi P',
    authorLocation: 'Johannesburg, South Africa',
    date: '2016-08-22',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r408653274-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '329195603',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent service',
    text: 'Very Nice and friendly people, we are glad we meet them they let us feel like home.\nA perfect organization and a wonderfull day. If you want to find out Mauritius is the best solution. Roberto and sabrina',
    author: 'Sabrina G',
    authorLocation: 'Rome, Italy',
    date: '2015-11-26',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r329195603-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '288101263',
    source: 'TripAdvisor',
    rating: 5,
    title: 'lovely',
    text: 'thanks to you guys memorable day we will make advert for you back home with friends it was the best holiday we had its a real paradise you are so lucky thanks to noorani and all the team .',
    author: 'juliemolly',
    authorLocation: 'Wales, United Kingdom',
    date: '2015-07-12',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r288101263-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '225182036',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Exellent service',
    text: 'I was in Mauritius first time. So they help to choose the best routes to see all interest places in Mauritius, we saw the places, which are not included in our excursions. We have 3 excursions, and one driver Cadio. He showd us a lot of interesting places and speak many interesting things. It was the most interesting and cognitive trip. And if we return I think we choose this service again.',
    author: 'Marina120988',
    authorLocation: 'Moscow, Russia',
    date: '2014-08-28',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r225182036-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '201407941',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Mauritious Tours',
    text: 'wonderful locally operated agency very experienced and professional. They know the Island very well and they can offer you tours of all types adapted to all needs and expectations. I highly recommend Noorani and Satar´s company to see the best of Mauritius.',
    author: 'conchi abejon',
    authorLocation: 'Alcala De Henares, Spain',
    date: '2014-04-16',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r201407941-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '724785169',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Fantastic!!',
    text: 'We met Belinda selling her sea excursions whilst on the beach at Lux Belle Mare. We decided on a half day speed boat excursion to the South Coast, what a fantastic day! We were met by Belinda’s sonWho was very friendly and introduced us to our crew for the day, Emily and Robin. What a great day from start to finish, feeding monkeys, waterfalls, snorkelling, surf cove, rum and coke and lots of laughs. A fantastic day at a very reasonable price. Definitely recommended',
    author: 'dianehughes59',
    authorLocation: 'Javea, Spain',
    date: '2019-11-07',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r724785169-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '691083469',
    source: 'TripAdvisor',
    rating: 5,
    title: "Can't recommend enough!",
    text: "We stayed in Belle Mare and originally booked excursions with Connections who were provided through Thomas Cook. Connections weren't very good so we canceled with them and went to Belle Mare tours, who not only turned out to be cheaper, but also the staff and drivers were much more friendly. These guys were very easy to book with and even booked an excursion past their closing time through whatsapp. They were always happy to help and played a big part in making our holiday as enjoyable as it was. I can't recommend these guys enough. They also don't require payment until after the excursions or trips have finished.",
    author: 'David R',
    authorLocation: 'Margate, United Kingdom',
    date: '2019-07-20',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r691083469-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '683425399',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Speed boat at Benetier',
    text: 'Amazing experience! We booked speed boat at Benetier including swimming with the dolphins, snorkelling and lunch BBQ at Benitier Island. Really enjoyed throughout. Price was fair about 2000 Rupees per person with transport included. I did booking without prior payment required. I must also highlight that they are very honest and doesnt just sell their product. They sell their product because they want you to enjoy your holiday. Highly recommended!',
    author: 'bilqis',
    authorLocation: 'United Kingdom',
    date: '2019-06-22',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r683425399-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '669197190',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Well organised ',
    text: 'Booked our airport transfers and three other tours with the company and was very happy with the service. Nagesh was always on hand to attend to queries and communicated on time with details of the driver and pick up times. Our driver/guide Jean Michel was very good and gave us some really useful information on the places we visited.',
    author: 'Chita K',
    authorLocation: 'Lusaka, Zambia',
    date: '2019-04-25',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r669197190-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '531577009',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent Tour Company and Great Value for Money',
    text: 'Used Belle Mare Tours for both the South and North Tours of the Island.  Our driver and guide, Kadr, was first class.  He is knowledgeable and clearly in love with his Island.  He was attentive and informative offering good advice at all times and he added a lot of local experience to our experience.  He also instinctively knew when to step back and allow us the space and time to fully appreciate and enjoy the many attractions on these tours.',
    author: 'DTF_LJF',
    authorLocation: 'Larkhall, United Kingdom',
    date: '2017-10-09',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r531577009-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '507430948',
    source: 'TripAdvisor',
    rating: 5,
    title: 'These guys are excellent',
    text: "About half the price of hotel services. Offer exactly the same thing. Prompt service, really good days out. \n\nOn one occasion we unwittingly overpaid a driver, he didn't realise until after we came back from a catamaran tour but met us to give us the money back.\n\nHonest, lovely people.",
    author: 'MeatySays',
    authorLocation: null,
    date: '2017-07-31',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r507430948-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '482805172',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Awesome Service',
    text: 'I stayed at the Solana Beach Hotel for a week from 27 April - 4 May and during this time, I made use of Belle Mare Tour for some excursions. They were swift to respond to my emails, tolerant when I postponed booked tours due to bad weather and always available to help. I will definitely make use of them when i go to Mauritius again.\n\nMy driver Vikash Sohodeb was an absolute delight. \n\nWay to go guys!!',
    author: 'Cindy S',
    authorLocation: 'Cape Town Central, South Africa',
    date: '2017-05-08',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r482805172-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '449906847',
    source: 'TripAdvisor',
    rating: 5,
    title: 'The best prices and very good services',
    text: 'We booked all of our Mauritius tours and taxi rides via Belle Mare and got a very service. The prices are great! In fact the best prices on the island. The people are responsive and helpfull! \n\nHighly recommend!',
    author: 'Cristian I',
    authorLocation: null,
    date: '2017-01-06',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r449906847-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '449261365',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great operator and price',
    text: 'Used Belle Mare tours for my airport transit to long beach and back and also a trip to the local market. The were the quickest to respond in regards with pricing and were very competitive. They were also on time as scheduled and also changed my departure time with very short notice, fantastic operator. Thank you very much to our rivers Jean Michael and Riaem they were great, very helpful and patient.',
    author: 'LukeGP',
    authorLocation: 'Johannesburg, South Africa',
    date: '2017-01-04',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r449261365-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '446737635',
    source: 'TripAdvisor',
    rating: 5,
    title: 'south island tour',
    text: 'We booked  a southern island trip which was amazing. Picked up by modern top spec Toyota at 9 am. Driver was informative, friendly, helpful. 2200 rupees for a duration of 7 hours - amazing value - give the guys a good tip, they deserve it.',
    author: 'maurice g',
    authorLocation: 'Brixworth, United Kingdom',
    date: '2016-12-26',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r446737635-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '428338926',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Two must go tours',
    text: 'We booked with Belle Mare Tours two different tour, the South Tour, a car tour where you visit the main spots of the south part of the Mauritius Island, where you have the opportunity to know a little bit more the geography and culture of Mauritius, and the we booked the Ile aux Cerfs tour, a tour by boat where you visit one of the main islands on the East Side. The service in both tours (and particularly in the Iles aux Cerfs tour) was top notch, and the price seemed very very fair, more or less half price of what the equivalent tour organized by the Hotel. The owners, Satar and Noorani are good ambassadors of the island sympathy and focus on the client. Highly Recommended',
    author: 'NunoVaz',
    authorLocation: null,
    date: '2016-10-16',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r428338926-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '396099315',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent service',
    text: 'Used Belle Mare Tours for transfers and trips,excellent service,highly recommend to use, great prices too',
    author: 'William W',
    authorLocation: 'Belfast, United Kingdom',
    date: '2016-07-24',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r396099315-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '384951462',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent service',
    text: 'After reading the reviews on TA we emailed from the UK to book our airport transfers plus the north tour and day trip to Casela.  All pick ups were prompt and on time, drivers polite and courteous.  \nWould highly recommend and we would definitely use again when we return.',
    author: 'silva2010',
    authorLocation: 'Basingstoke, United Kingdom',
    date: '2016-06-22',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r384951462-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '380802399',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great tours at great prices',
    text: "We were advised by other guests at the Emeraude hotel to use these for trips as they are much better priced than the trips by your holiday rep and they were right. \nWe booked the north of the island trip and our guide was great, he was on time, in a nice clean and smart vehicle. He was chatty without going overboard and unfortunately I don't remember his name.\nOur second trip was with Sunil who took us to the south and again he told us all about the island, pointed things out and was genuinely a nice guy. \nAll the drivers appear to be knowledgeable, friendly and all the cars are clean and have air-conditioning even when going into the office they are helpful but not pushy which is great.\n\nA big thank you to you all :-)",
    author: 'Noodle2022',
    authorLocation: 'Newcastle upon Tyne, United Kingdom',
    date: '2016-06-08',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r380802399-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '371797308',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Belle Mare Tours made our stay at Mauritius worthwhile',
    text: 'We were recommended Belle Mare Tours by our host at Mauritius. We were glad that we listened to the host and went with Belle Mare Tours to plan our activities and take us around Mauritius. They were extremely helpful, courteous and proactive in providing us the best experience. All the activities that were planned were executed to the minutest detail. \n\nA big shout out to the coordinator Nagesh who was always eager to respond to our endless queries, and to the driver Abdul who was treating us as their family rather than mere guests.\n\nHighly recommended tour operator while at Mauritius.',
    author: 'RiteshVG',
    authorLocation: 'Bengaluru, India',
    date: '2016-05-10',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r371797308-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '338533343',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great Days Out',
    text: 'We had two amazing days out. One the catamaran trip to the North Islands. Great food on the cat , some pleasant snorkelling  , fantastic company , well organised and clean boat.\nAnd one on the speed boat to blue bay , the old lighthouse island ..Food was cooked and served on the quiet side of ile aux cerfs , lobster, chicken and fish.This was superb. Beautifully cooked and finished off with bananas and rum cooked on the bbq.All washed down with wine , and naturally, different flavoured drums.\nThese two trips are fun days out with some lovely scenery. They are a must to do if you like being at sea. Great value. Thank you so much to all the crew of both boats our pickup drivers ., Not forgetting Jack Sparrow !',
    author: 'UkChristina',
    authorLocation: null,
    date: '2016-01-08',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r338533343-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '330113894',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Mrs',
    text: 'A really excellent trip would definitely do it again. It was a really good price, had a lovely lunch one of the best meals we had whilst in Mauritius.',
    author: 'natpugh',
    authorLocation: null,
    date: '2015-12-01',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r330113894-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '281586805',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Boat Trip',
    text: 'Lovely Speed boat trip with "Captain Jack" good value for money and great day out. Good BBQ on beach at Ile De Cerfs',
    author: 'carol51054',
    authorLocation: 'Farnborough, United Kingdom',
    date: '2015-06-20',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r281586805-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '275260773',
    source: 'TripAdvisor',
    rating: 5,
    title: 'catamaran to Gabriel Island and Flat Island',
    text: 'A fantastic trip with delicious bbq on board. The crew were great - really friendly - and the snorkelling was fantastic! \nDefinitely recommended and a great price too! Take plenty of sun cream and your snorkelling gear!',
    author: 'Lorraine M',
    authorLocation: 'Worthing, United Kingdom',
    date: '2015-05-28',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r275260773-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '243446616',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent Service at Great Prices',
    text: 'We used their services in November when we visited Mauritius for a week. All our travel around the island was organised through them and the cars arrived on time with great drivers who served as tour guides as well. The Rates were the cheapest we could find. The highlight of our trip was the speedboat trip across the island which lasted a day. Mr Noorani was very helpful and made our trip truly memorable.',
    author: 'Jaikar J',
    authorLocation: 'Dubai, United Arab Emirates',
    date: '2014-12-08',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r243446616-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '1029898897',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Vacation Belle Mare Tours',
    text: 'Thank you very much to Rony for organizing our stay in Mauritius. The planning is really done according to the weather, to allow us to enjoy the best possible conditions. \nAnd a big thank you to Ali, our taxi, for bringing us on the different activities while advising us, guiding us, and this throughout our stay!',
    author: 'baptiste d',
    authorLocation: null,
    date: '2025-09-11',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r1029898897-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '1025004151',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent tour company ',
    text: "After researching different companies for tours we settled with Belle Mare and we were not disappointed. From our very first contact they were efficient and responsive and adapted to what we wanted to see and do and also offered suggestions.\n\nWe opted for a North Tour and a South Tour and then a bespoke tour for our third trip.  Driver arrived at our hotel on time and they were friendly and knowledgeable.  With planning we were able to see a lot of the island over three days.\n\nWe had driver Ali for two of them (great guy!) and on our north tour he took us into Port Louis,  something we wouldn't have done alone.\n\nCan highly recommend and would definitely use again if we have a opportunity to return to Mauritius.",
    author: 'Rob121618',
    authorLocation: 'West Malling, United Kingdom',
    date: '2025-08-17',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r1025004151-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '989689019',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Day in paradise',
    text: 'Beautiful excursion, rich in emotions, in a boat, super cool, with music, stops at deer island and ,\n the island of lighthouses in particular! Great meal, with grilled chicken, grilled fish, great flaming fruit',
    author: 'Laura I',
    authorLocation: null,
    date: '2025-01-18',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r989689019-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '928470708',
    source: 'TripAdvisor',
    rating: 5,
    title: '5 Island Speed Boat Trip',
    text: 'Well, what can we say ... Absolutely amazing!!! We did the 5 island trip with Belle Mare Tours on a private speed boat today (5th December 23). \n\nExcellent service from start to finish, and our skipper Chris was first class. He explained everything clearly and took our safety a priority Highly recommend. We had an amazing day. 👏',
    author: 'Flo20450',
    authorLocation: 'Manchester, United Kingdom',
    date: '2023-12-05',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r928470708-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '888101256',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Tours in Mauritius',
    text: 'We used Belle Mare Tours after they were recommended by somebody at our hotel  Sunrise attitude. Geerja was very professional and knowledgeable in helping us decide which tours to do. We did 3 all day tours which were excellent but the Blue Cruise was amazing.  We saw dolphins and our captain Desailly was excellent and adapted our private tour to suit us. Good time had by all, highly recommended.',
    author: 'Malcolm J',
    authorLocation: null,
    date: '2023-04-28',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r888101256-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '861175232',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great private trip',
    text: 'Great private Catamaran trip for a group of 7 couples. The crew were great and ensured drinks flowed from beginning to end. The BBQ cooked on the back of the catamaran was delicious, as were the rice, pasta and bread side dishes. Plenty of good music, dancing and all requests for different tracks accommodated. Consensus of opinion amongst all of us gives this trip and the crew 20 out of 10! Highly recommend it!',
    author: 'R0sie16',
    authorLocation: 'Great Ayton, United Kingdom',
    date: '2022-09-21',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r861175232-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '854469286',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Brilliant Tours with Belle Mare Tours',
    text: 'We have just done two excursions with Belle Mare tours, Southern Tour and Swimming with Dolphins including snorkelling and a BBQ on Benitier Island. Both were brilliant experiences, well organised and great value for money. The dolphin swimming was a real memory maker, the crew were great at getting you in the water at the right place to get you up close with the Dolphins. Both trips were made all the better for having Mike as our host for the tour and as taxi. Thanks Belle Mare and thank you Mike.',
    author: 'Kev O',
    authorLocation: null,
    date: '2022-08-16',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r854469286-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '846259465',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Amazing',
    text: 'Met Belinda on the beach , she recommended the best day to go ( weather wise) chose the 8 hour trip which I highly recommend. We were a family of 2 adults and 2 kids age 9 and 5 . Our captain and co host was robin and Emily and they were both amazing and couldn’t do enough for us 😊 . The trip was was of our best ever , beautiful waterfalls , feeding monkeys , up close to dolphins and I mentioned I liked fishing before so they put a rod on the boat and we caught fish . Stopped off at a deserted lighthouse with stunning views , my son got to drive the boat which he loved , few Mauritian  coffee 😉 too . Finished off on a private beach eating fresh lobster / fish chicken , wine . Amazing day . Don’t miss out if your heading to Mauritius, go see Belinda 👌🏽👌🏽 \n\nThanks once again 😘😘',
    author: 'davidivins',
    authorLocation: 'Cardiff, United Kingdom',
    date: '2022-07-04',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r846259465-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '746293909',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Good trips by Belle Mare Tours',
    text: 'I read some reviews here of this agency, but honestly they sounded too good to be true. \nWe had the most amazing 3 trips organized by the team of Belle Mare tours - very high quality, good price and professional. \nWhen i am next in Belle Mare - i am using them again!',
    author: 'I B',
    authorLocation: 'London, United Kingdom',
    date: '2020-02-20',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r746293909-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '739911569',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent Service/ Highly Recommended',
    text: "we booked 3 tours and one taxi service. couldn't have asked for more. Covered South/North/5 Island tours. Drivers arrived on time/ knew what they were doing/ did everything right by us. Very happy with their services. Ask for Mike if you have a choice as he is really good.",
    author: 'Prasad B',
    authorLocation: 'Perth, Australia',
    date: '2020-01-18',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r739911569-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '732747275',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Perfect!',
    text: 'We hired a car for two days with this company and everything was perfectly arranged. The car was brought to our hotel in the evening so we could leave early the next day. Very good service. We also did the blue island tour, which was very well organised and much fun! And reasonable prices. Definitely recommend!',
    author: 'Taraberg',
    authorLocation: 'Zakynthos, Greece',
    date: '2019-12-14',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r732747275-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '728649146',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Amazing experience',
    text: 'We visited Mauritius,  south african family trip with my husband, 5 year old son and his grandma. We did the south, north and speed boat tour. The guides are very knowledgeable and we learned so much. They communicated very well and they were always on time. Booking the tours were a breeze.They are affordable as well. Would definitely recommend.',
    author: 'Anon ct',
    authorLocation: null,
    date: '2019-11-24',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r728649146-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '727712976',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great Transfer',
    text: 'He had asked Belle Mare tours for 3 Transfer and transport services. The drives were always very cordial and always on time. Good prices, it was really a nice experience.',
    author: 'Priscila Coutinho',
    authorLocation: 'Brazil',
    date: '2019-11-20',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r727712976-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '727655757',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Just great!',
    text: 'Great price comparing to other companies. Great and safe driver Tader picked us up on time and told us some historical stories of the island and he knows everything about trees and plants. Such a fun time to be in the car with him. He makes sure he drives safely and we were not scared in the car.\nThe tours are amazing. We did the hiking, south tour, dolphin tour and hired Tader to drive us around for the day.\nPerfect service, quick responses, polite, great value for money.\nBook with this agency when you go!',
    author: 'Isabella C',
    authorLocation: null,
    date: '2019-11-19',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r727655757-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '718594821',
    source: 'TripAdvisor',
    rating: 5,
    title: 'we went out on glass bottom boat and did some snorekeling',
    text: 'All very good but due to an anti cyclone in the area the boats were suspended for 3 days which was very disappointing',
    author: 'una20182018',
    authorLocation: 'Dublin, Ireland',
    date: '2019-10-15',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r718594821-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '717077496',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great tours',
    text: "We booked the South Tour and hiking Le Morne, we couldn't be happier!\nEverything from booking to pick up went smoothly and the communication was easy. The prices for the tours are much better than the ones you get in the hotels.\nThe south tour is a must for everyone visiting Mauritius! Hiking Le Morne is challenging and some people just gave up in the middle, but it's absolutely worth the sweat, as the views are amazing.\nWe'd like to thank our driver Sunil - he was always right on time, knowledgeable and with a great sense of humor! He explained us everything from the history of the island to specific information for the places we've been to, so this made the ride really enjoyable.",
    author: 'Teodor',
    authorLocation: 'Sofia, Bulgaria',
    date: '2019-10-10',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r717077496-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '713161632',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Excellent bespoke tour',
    text: 'We felt very fortunate to find Belle Mare tours via Tripadvisor. They were quick to respond to my online enquiry then prompt to get back to me with a competitive quote (much cheaper than hotel!). Mr Mansoor arrived on time and in a great car. We particularly wanted to go to La Vanille Crocodile Park and then to a market. This is exactly what Mr Mansoor did. It was refreshing to have an excellent English speaking guide who also didn’t deviate from the route. He suggested a lovely cliff top spot for our picnic lunch and gave us some local info about life in Mauritius. On the way back, he bought us some fresh Indian snacks from a local shop and refused to take any money for them. Such a treat! We had a wonderful day and would highly recommend this company and in particular Mr  Mansoor as your driver.',
    author: 'Emmaj432',
    authorLocation: 'Tonbridge, United Kingdom',
    date: '2019-09-26',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r713161632-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '712781232',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great tours',
    text: 'Tour guides are very knowledgeable,friendly and know the best places to visit. They give you ample time when visiting places and ensure that you are happy and safe.',
    author: 'sanjirajdew',
    authorLocation: null,
    date: '2019-09-24',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r712781232-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '707178652',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Fantastic, efficient and very reasonable price',
    text: "We've booked the South Tour, South Island hopping speed boat trip and scuba diving trips with Bellemare Tour. \nThey arrived on time and much more competitive price than the hotel operators we are staying with. Negash was so helpful and cannot do enough for us. \nThe speed boat trip was just the best. The guide was very understanding with we have young children (2 four years old boys). And they thoroughly loved it. \nWe paid a private boat for us which I think it helped. \nHighly recommended.",
    author: 'Christy Ho',
    authorLocation: 'Reading, United Kingdom',
    date: '2019-09-06',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r707178652-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '699699552',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great tours with Mansoor!',
    text: 'My friend and I booked the North tour and the South tour. We were lucky to have Mansoor as our driver and guide both days. He made the tours even more enjoyable. Very friendly and accommodating. He even had us try some special Mauritian treats that we enjoyed a lot. I wanted to make sure I wrote a good review because of Mansoor. Thank you very much for making us feel welcome and showing us around. :D',
    author: 'KPKPMK',
    authorLocation: 'Minnesota',
    date: '2019-08-16',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r699699552-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '699222046',
    source: 'TripAdvisor',
    rating: 5,
    title: 'It was indeed a paradise ',
    text: 'Exceptional service from pick up till drop off, Our guide Mike is a professional and truly confident I couldn’t describe how much me and my family enjoyed everything about this tour...my daughter says it’s more than a paradise🥰 the food is the icing of all, will definitely come back for more island hoping hopefully next year.',
    author: 'Lea R',
    authorLocation: 'Dubai, United Arab Emirates',
    date: '2019-08-15',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r699222046-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '684797708',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Great island speedboat tour!!',
    text: 'Great tour!! We had so much fun and enjoyed our turist guides!! \nVisited a couple of islands with snorkling with the dish and had a perfect lunch at one of the islands with lots of wine and rum! It was perfect!!',
    author: 'akutlesa',
    authorLocation: 'Rijeka, Croatia',
    date: '2019-06-27',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r684797708-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '672511069',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Trusted and professional',
    text: 'I booked single trip from Shangeri-la to Outrigger hotel. They helped in acceptong in $$, On time, safe and relaiable.',
    author: 'E A',
    authorLocation: 'Riyadh Province, Saudi Arabia',
    date: '2019-05-08',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r672511069-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '668466442',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Swimming With Dolphins',
    text: 'Well organised trip and best price by a mile. Half the price of LongBeach recommended agent.\nPicked up at 6am and back at hotel by 11.30am so don’t miss the sun!!',
    author: 'mikedf1973',
    authorLocation: null,
    date: '2019-04-22',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r668466442-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '643438235',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Catarmarant rip',
    text: 'Wonderful day, the crew were very experienced, the boat was immaculate and the lunch was very generous. Thank you',
    author: 'Experience680546',
    authorLocation: null,
    date: '2019-01-03',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r643438235-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '638754762',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Best tour company',
    text: "I'm all my travels, I must say that Nagesh and Noorani of Bella.Mare tours did a splendid job in arranging my transfers, and fixing up my itinary for 4 days. The driver especially Robert Joy was so polite ,warm and and helpful  to my needs. I highly recommend Belle Mare tours to everyone who is visiting Mauritus. They do not over charge and very trustworthy.",
    author: 'kingleo2015',
    authorLocation: 'Thiruvananthapuram (Trivandrum), India',
    date: '2018-12-11',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r638754762-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '607153241',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Blissful Holiday',
    text: 'I would recommend this resort as the moment you arrive you are made to feel very special. The wonderful staff are so friendly and go out of their way to make you feel so welcome.',
    author: 'Asha Patel',
    authorLocation: null,
    date: '2018-08-16',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r607153241-Belle_Mare_Tours-Belle_Mare.html',
  },
  {
    id: '602049424',
    source: 'TripAdvisor',
    rating: 5,
    title: 'Good comms, competitive price',
    text: "I arranged, at short notice, a car with driver to take my family on a tour of the South including Black River Gorges, the dormant volcano, Chamarel, Grande Bassin; the car provided was a 6 seater, helpful driver Jean Michel, cost of Rs 2600. I wouldn't hesitate to use them again.",
    author: 'ukpsychiatrist',
    authorLocation: 'London, United Kingdom',
    date: '2018-08-02',
    url: 'https://www.tripadvisor.com/ShowUserReviews-g298342-d6553120-r602049424-Belle_Mare_Tours-Belle_Mare.html',
  },
];
