// AUTO-GENERATED by scripts/gen-review-pool.mjs from data/belle-mare-tours-reviews.json. Do not edit by hand.
import type { ReviewTopic } from './review-topics';

/** Per-topic aggregate over the RESOLVED review set (topics under the minimum collapse to
 *  `general`), so a listing card's rating always matches its detail page's review block. */
export const TOPIC_STATS: Record<ReviewTopic, { avg: number; count: number }> = {
  "general": {
    "avg": 4.8,
    "count": 1076
  },
  "catamaran": {
    "avg": 4.8,
    "count": 208
  },
  "speedboat": {
    "avg": 4.9,
    "count": 99
  },
  "dolphin": {
    "avg": 4.8,
    "count": 69
  },
  "hiking": {
    "avg": 4.8,
    "count": 96
  },
  "sightseeing": {
    "avg": 4.7,
    "count": 554
  },
  "transfer": {
    "avg": 4.7,
    "count": 396
  },
  "rental": {
    "avg": 4.8,
    "count": 37
  },
  "water": {
    "avg": 4.7,
    "count": 170
  },
  "air": {
    "avg": 4.8,
    "count": 1076
  }
};
