// AUTO-GENERATED by the SEO content workflow (gytm-seo-content). Do not edit by hand.
import type { TransferContent } from './transfers';

export const TRANSFERS_RAW: TransferContent[] = [
  {
    "slug": "lux-belle-mare",
    "hotelName": "LUX* Belle Mare",
    "area": "Belle Mare",
    "region": "East",
    "distanceKmFromAirport": 45,
    "durationMinFromAirport": 50,
    "intro": "Start your stay at LUX* Belle Mare the easy way with a pre-booked private transfer from SSR International Airport. The drive up the east coast takes roughly 50 minutes, so you reach the hotel relaxed and on time. Your local driver-guide speaks English and French, greets you at arrivals, helps with your bags and takes you straight to the door. The price is fixed and transparent, agreed when you book, with no meter and no surprises. Just confirm your flight details and we handle the rest, door to door.",
    "included": [
      "Meet and greet at arrivals with a personalised name board",
      "Flight tracking so your pickup adjusts automatically to delays",
      "Free first child or baby seat on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water in the vehicle",
      "Door-to-door drop-off at LUX* Belle Mare with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Belle Mare Beach",
      "Île aux Cerfs",
      "Centre de Flacq market",
      "Belle Mare Plage golf course",
      "Poste Lafayette",
      "Bras d'Eau National Park"
    ],
    "faq": [
      {
        "q": "How long is the transfer to LUX* Belle Mare?",
        "a": "The drive from SSR International Airport to LUX* Belle Mare is around 45 km and normally takes about 50 minutes by private car, depending on traffic and the time of day."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. Your first child or baby seat is free of charge, just tell us the child's age when you book so we can fit the right type. Extra seats can be added on request."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time and adjust the pickup automatically, so your driver is there when you land. You also get up to 60 minutes of free waiting time at no extra cost."
      },
      {
        "q": "Can I book a return or departure transfer?",
        "a": "Yes. You can book a one-way transfer or add the return leg back to the airport at the same time. For departures we schedule the pickup to fit your check-in, with comfortable time to reach SSR."
      }
    ]
  },
  {
    "slug": "constance-belle-mare-plage",
    "hotelName": "Constance Belle Mare Plage",
    "area": "Belle Mare",
    "region": "East",
    "distanceKmFromAirport": 45,
    "durationMinFromAirport": 50,
    "intro": "Constance Belle Mare Plage sits on the east coast, about 45 km from SSR International Airport in the south-east. The drive takes roughly 50 minutes via Plaine Magnien and the east-coast road. We run a door-to-door private transfer with a local driver who speaks English and French, so there's no airport queue and no shared shuttle. Your driver meets you inside arrivals with a name board, helps with your luggage, and takes you straight to the hotel. The price is fixed and agreed when you book, with no meter and no surprises on arrival.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Flight tracking, so your driver adjusts the pickup time if your flight is early or delayed",
      "One free child or baby seat on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water in the vehicle",
      "Door-to-door drop-off at the hotel entrance with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Belle Mare public beach and lagoon",
      "Ile aux Cerfs island and its beaches",
      "Bras d'Eau National Park",
      "Poste Lafayette and the north-east coastline",
      "Trou d'Eau Douce fishing village",
      "Centre de Flacq market"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Constance Belle Mare Plage?",
        "a": "The drive from SSR International Airport to Constance Belle Mare Plage is about 45 km and usually takes around 50 minutes, depending on traffic and the time of day. Your private driver takes the most direct route along the east coast."
      },
      {
        "q": "How much luggage can I bring?",
        "a": "A standard car comfortably fits two passengers with two large suitcases plus hand luggage. If you are travelling as a family or group, or with golf bags or extra cases, just tell us the number of passengers and bags when booking and we'll send a larger vehicle."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. The first child or baby seat is free on request. If you need more than one, let us know the children's ages when you book so we can fit the correct seats before pickup."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so your driver adjusts the pickup time automatically if you land early or late. You also have up to 60 minutes of free waiting after landing while you clear immigration and collect your bags, so there's no need to worry about delays at no extra cost."
      }
    ]
  },
  {
    "slug": "long-beach-mauritius",
    "hotelName": "Long Beach Mauritius",
    "area": "Belle Mare / Poste de Flacq",
    "region": "East",
    "distanceKmFromAirport": 45,
    "durationMinFromAirport": 50,
    "intro": "Belle Mare Tours runs pre-booked private airport transfers from SSR International Airport to Long Beach Mauritius in Belle Mare on the east coast. The drive takes about 50 minutes through the sugar-cane plains and coastal villages of Poste de Flacq. Your local driver-guide, who speaks English and French, meets you at arrivals with a name board and takes you door to door in a private air-conditioned car. The price is fixed and agreed when you book, with no meter and no surprises. Just send your flight details and we handle the rest, from landing to your hotel reception.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Flight tracking so your driver adjusts the pickup time to any delay",
      "First child or baby seat free on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water in the car",
      "Door-to-door drop-off at the Long Beach Mauritius reception",
      "Instant email confirmation with your driver and trip details"
    ],
    "nearbyAttractions": [
      "Belle Mare public beach and lagoon",
      "Île aux Cerfs and its offshore lagoon",
      "Centre de Flacq market",
      "Poste de Flacq and the Sagar Shiv Mandir temple by the sea",
      "Bras d'Eau National Park",
      "Anahita and Belle Mare Plage golf courses"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Long Beach Mauritius?",
        "a": "The private transfer from SSR Airport to Long Beach Mauritius in Belle Mare covers roughly 45 km and takes about 50 minutes by car, depending on traffic and the time of day."
      },
      {
        "q": "How much luggage can the car take?",
        "a": "A standard saloon car comfortably fits two large suitcases plus two cabin bags for two passengers. If you are travelling with more luggage, a family, or sports equipment such as golf bags, just tell us when booking and we will send a larger vehicle."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. The first baby or child seat is free on request, and additional seats can be arranged. Let us know your children's ages when booking so we fit the correct seat."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so your driver automatically adjusts the pickup time to your actual landing. You also get up to 60 minutes of free waiting after touchdown, so there is no need to worry about delays at immigration or baggage."
      }
    ]
  },
  {
    "slug": "shangri-la-le-touessrok",
    "hotelName": "Shangri-La Le Touessrok",
    "area": "Trou d'Eau Douce",
    "region": "East",
    "distanceKmFromAirport": 50,
    "durationMinFromAirport": 55,
    "intro": "Shangri-La Le Touessrok sits on the east coast at Trou d'Eau Douce, about 50 km from SSR International Airport in the south-east. We run a door-to-door private transfer in a comfortable air-conditioned car, so you skip the taxi queue and ride straight to the resort with a local English- and French-speaking driver. The price is fixed and agreed when you book, with no meter and no surprises on arrival. Your driver meets you inside the arrivals hall with a name board and helps with the luggage. The scenic drive north through the villages takes roughly 55 minutes.",
    "included": [
      "Meet and greet inside the arrivals hall with a personal name board",
      "Flight tracking so your pickup time adjusts automatically to any delay",
      "Free first child or baby seat fitted on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at the entrance of Shangri-La Le Touessrok with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Île aux Cerfs island and its lagoon, reached by boat from Trou d'Eau Douce",
      "Grand River South East (GRSE) Waterfall boat trip",
      "Belle Mare public beach and the long east-coast sands",
      "Bras d'Eau National Park for forest walks and birdwatching",
      "Poste Lafayette and the kitesurfing flats further north",
      "Centre de Flacq market for local food and shopping"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to Shangri-La Le Touessrok?",
        "a": "The drive from SSR Airport to Trou d'Eau Douce is about 50 km and usually takes around 55 minutes in our private car, depending on traffic and the time of day."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time, so your driver adjusts the pickup to your actual landing time. You also get up to 60 minutes of free waiting after you land at no extra cost."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. Your first child or baby seat is free, fitted to your child's age on request. Just tell us the ages when you book so we bring the right seat."
      },
      {
        "q": "Can I book a return or departure transfer back to the airport?",
        "a": "Yes. You can add a departure transfer when you book, and we will pick you up from the hotel at a time that gets you to the airport with comfortable check-in margin."
      }
    ]
  },
  {
    "slug": "ambre-mauritius",
    "hotelName": "Ambre Mauritius",
    "area": "Palmar",
    "region": "East",
    "distanceKmFromAirport": 45,
    "durationMinFromAirport": 50,
    "intro": "Ambre Mauritius sits on the calm east-coast beach at Palmar, just south of Belle Mare. From SSR International Airport in the south-east it is roughly a 45 km drive, about 50 minutes up the coast road. We run a door-to-door private transfer in a comfortable air-conditioned car with a local, English- and French-speaking driver who meets you in the arrivals hall by name. The price is fixed and agreed when you book — no meter, no surprises — so you can step off your flight and head straight to the hotel.",
    "included": [
      "Meet & greet inside the arrivals hall with a name board",
      "Flight tracking so your driver adjusts the pickup time if you land early or late",
      "First child or baby seat free on request",
      "Up to 60 minutes of free waiting after you land",
      "Bottled water in the car",
      "Door-to-door drop-off at the Ambre Mauritius entrance with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Belle Mare Beach",
      "Île aux Cerfs",
      "Trou d'Eau Douce fishing village",
      "Grand River South East Waterfall",
      "Centre de Flacq market",
      "Île aux Aigrettes nature reserve"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to Ambre Mauritius?",
        "a": "The drive from SSR Airport to Ambre Mauritius in Palmar is about 45 km and usually takes around 50 minutes in a private car, depending on traffic and the time of day."
      },
      {
        "q": "How much luggage can I bring?",
        "a": "A standard car comfortably fits two adults with two large suitcases and hand luggage. If you are travelling with extra bags, golf clubs or a larger group, tell us when you book and we will send a bigger vehicle at no surprise to you."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We provide the first baby or child seat free of charge — just add your child's age when booking so we fit the right type. Additional seats can be arranged on request."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight number, so your driver automatically adjusts to the new landing time. You also get up to 60 minutes of free waiting after you clear the arrivals hall, with no extra charge for normal delays."
      }
    ]
  },
  {
    "slug": "paradis-beachcomber",
    "hotelName": "Paradis Beachcomber",
    "area": "Le Morne",
    "region": "West",
    "distanceKmFromAirport": 55,
    "durationMinFromAirport": 65,
    "intro": "Paradis Beachcomber sits at the foot of Le Morne Brabant on the south-west coast, about 55 km from SSR Airport. Belle Mare Tours runs a door-to-door private transfer for this route, so a local English- and French-speaking driver meets you at the arrivals hall and takes you straight to the resort with no stops or shared vans. You pay a fixed, transparent price agreed when you book, with no meter and no surprises on arrival. The drive takes roughly 65 minutes through the south of the island, and your driver greets you by name at the airport.",
    "included": [
      "Meet and greet at the arrivals hall with a name board",
      "Flight tracking so your pickup adjusts automatically to delays",
      "One free child or baby seat on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water in the car",
      "Door-to-door drop-off at the Paradis Beachcomber reception",
      "Instant email confirmation with your driver's details"
    ],
    "nearbyAttractions": [
      "Le Morne Brabant UNESCO World Heritage mountain",
      "Le Morne public beach and kitesurfing lagoon",
      "La Gaulette fishing village",
      "Black River Gorges National Park",
      "Chamarel Seven Coloured Earths and waterfall",
      "Île aux Bénitiers boat trips and the Crystal Rock"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to Paradis Beachcomber?",
        "a": "The drive from SSR Airport to Paradis Beachcomber at Le Morne is about 55 km and usually takes around 65 minutes by private car, depending on traffic and the time of day."
      },
      {
        "q": "Are child and baby seats available?",
        "a": "Yes. The first child or baby seat is free when you request it at booking. Just tell us the child's age and we will fit the correct seat before pickup."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time, so your driver adjusts the pickup to your actual landing time. You also get up to 60 minutes of free waiting after you clear arrivals at no extra cost."
      },
      {
        "q": "Can I book a return or departure transfer too?",
        "a": "Yes. You can add a return transfer from Paradis Beachcomber back to the airport in the same booking, and we will schedule the pickup to suit your check-in time."
      }
    ]
  },
  {
    "slug": "dinarobin-beachcomber",
    "hotelName": "Dinarobin Beachcomber",
    "area": "Le Morne",
    "region": "West",
    "distanceKmFromAirport": 55,
    "durationMinFromAirport": 70,
    "intro": "Start your stay at Dinarobin Beachcomber the easy way with a pre-booked private transfer from SSR International Airport. Tucked beneath the iconic Le Morne Brabant on the south-west coast, the resort sits about 55 km from the airport, a scenic drive of around 70 minutes past the south coast. Your local English and French-speaking driver meets you at arrivals with a name board, helps with your bags and takes you door to door. The price is fixed and transparent, agreed before you travel, with no meter and no surprises on arrival.",
    "included": [
      "Meet and greet at the arrivals hall with a personalised name board",
      "Flight tracking so your driver adjusts the pickup time to any delays",
      "First child or baby seat provided free on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water in an air-conditioned vehicle",
      "Door-to-door drop-off at the Dinarobin Beachcomber entrance with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Le Morne Brabant UNESCO World Heritage mountain hike",
      "Le Morne public beach and kitesurfing lagoon",
      "Chamarel Seven Coloured Earth and Chamarel Waterfall",
      "Black River Gorges National Park viewpoints",
      "Casela Nature Parks near Cascavelle",
      "La Gaulette village and boat trips to Île aux Bénitiers"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Dinarobin Beachcomber?",
        "a": "The drive from SSR International Airport to Dinarobin Beachcomber in Le Morne is roughly 55 km and takes about 70 minutes in normal traffic, mostly along the motorway and the scenic south coast road. Travel times can be a little longer at peak hours or in heavy rain."
      },
      {
        "q": "How much luggage can the vehicle carry?",
        "a": "A standard private car comfortably fits two to three passengers with two large suitcases and hand luggage. If you are travelling with a larger group, extra bags, golf clubs or bulky equipment, just tell us when booking and we will assign a larger vehicle such as an SUV or minivan."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We provide your first child or baby seat free of charge on request, with options for infants, toddlers and boosters. Please add the ages of any children when you book so the right seat is fitted and ready in the car."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight number, so your driver automatically adjusts to the new landing time at no extra cost. You also get up to 60 minutes of free waiting after touchdown, giving you time to clear immigration and collect your bags without worry."
      }
    ]
  },
  {
    "slug": "lux-le-morne",
    "hotelName": "LUX* Le Morne",
    "area": "Le Morne",
    "region": "West",
    "distanceKmFromAirport": 58,
    "durationMinFromAirport": 70,
    "intro": "LUX* Le Morne sits on the wild south-western tip of Mauritius, beneath the UNESCO-listed Le Morne Brabant mountain. Belle Mare Tours runs pre-booked, door-to-door private transfers from SSR International Airport straight to the resort — roughly a 70-minute drive along the south coast. Your local, English- and French-speaking driver meets you at arrivals with a name board, helps with the luggage and takes you directly to the hotel. The price is fixed and agreed in advance, so there is no meter and no surprises. Just book ahead, send your flight number, and relax.",
    "included": [
      "Meet & greet at the arrivals hall with a personalised name board",
      "Flight tracking, so your pickup time adjusts automatically if your flight is early or delayed",
      "Free first child or baby seat on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water in the car",
      "Door-to-door drop-off at the LUX* Le Morne entrance with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Le Morne Brabant (UNESCO World Heritage hike)",
      "Le Morne public beach and kitesurfing lagoon",
      "Chamarel Seven Coloured Earths and Chamarel Waterfall",
      "Black River Gorges National Park",
      "La Gaulette village and boat trips to Île aux Bénitiers",
      "Crystal Rock in the Le Morne lagoon"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to LUX* Le Morne?",
        "a": "The drive from SSR International Airport to LUX* Le Morne is about 58 km and usually takes around 70 minutes, depending on traffic and the time of day. The route runs along the scenic south coast of the island."
      },
      {
        "q": "How much luggage fits in the car?",
        "a": "A standard private car comfortably takes two large suitcases plus hand luggage for up to three passengers. If you are travelling with more bags, golf clubs or a larger group, let us know when you book and we will assign a bigger vehicle."
      },
      {
        "q": "Are child and baby seats available?",
        "a": "Yes. Your first child or baby seat is free of charge — just tell us the child's age when booking so we fit the correct seat. Additional seats can be arranged on request."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so your driver's pickup time adjusts automatically to the actual landing time. You also get up to 60 minutes of free waiting after touchdown, giving you time to clear immigration and collect your bags at no extra cost."
      }
    ]
  },
  {
    "slug": "st-regis-mauritius",
    "hotelName": "The St. Regis Mauritius Resort",
    "area": "Le Morne",
    "region": "West",
    "distanceKmFromAirport": 58,
    "durationMinFromAirport": 70,
    "intro": "The St. Regis Mauritius Resort sits at the foot of Le Morne Brabant on the island's southwest peninsula, about a 70-minute drive from SSR International Airport. Belle Mare Tours runs a private, door-to-door transfer straight to the resort lobby with a licensed local driver who speaks English and French. You travel in a comfortable air-conditioned car at a fixed, transparent price agreed before you book, with no meter and no surprises. Your driver meets you in the arrivals hall with a name board, helps with your luggage and takes the scenic south-coast route to Le Morne.",
    "included": [
      "Meet and greet inside the arrivals hall with a personal name board",
      "Flight tracking so your pickup time adjusts automatically to early or delayed arrivals",
      "One complimentary child or baby seat on request",
      "Up to 60 minutes of free waiting time after you land",
      "Bottled water on board your air-conditioned vehicle",
      "Door-to-door drop-off at The St. Regis Mauritius Resort reception, with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Le Morne Brabant UNESCO World Heritage mountain hike",
      "Le Morne public beach and lagoon kitesurfing spots",
      "Underwater Waterfall viewpoint near the peninsula",
      "Black River Gorges National Park",
      "La Vanille Nature Park and Chamarel Seven Coloured Earths",
      "Chamarel Waterfall and Rhumerie de Chamarel"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to The St. Regis Mauritius Resort?",
        "a": "The drive from SSR International Airport to Le Morne is roughly 58 km and takes about 70 minutes in a private car, depending on traffic and the time of day. Your driver takes the most comfortable route along the south coast."
      },
      {
        "q": "How much luggage can I bring?",
        "a": "A standard saloon car comfortably fits two large suitcases plus hand luggage for up to three passengers. If you are travelling as a family or group, or carrying golf bags, surfboards or extra cases, just tell us when booking and we will assign a larger vehicle at no surprise cost."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. Your first child or baby seat is free of charge, fitted and ready in the car when you arrive. Let us know your children's ages at booking so we can bring the correct infant, toddler or booster seat for the journey to Le Morne."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight number, so your driver always knows the real landing time and adjusts the pickup automatically. There is no extra charge for delays, and you get up to 60 minutes of free waiting time after touchdown while you clear immigration and collect your bags."
      }
    ]
  },
  {
    "slug": "sugar-beach-mauritius",
    "hotelName": "Sugar Beach Mauritius",
    "area": "Flic-en-Flac / Wolmar",
    "region": "West",
    "distanceKmFromAirport": 48,
    "durationMinFromAirport": 55,
    "intro": "Sugar Beach Mauritius sits on the soft sands of Wolmar, just south of Flic-en-Flac on the island's west coast. From SSR International Airport in the south-east the drive takes roughly 55 minutes across the central plateau and down to the coast. Belle Mare Tours runs a door-to-door private transfer with a local, English- and French-speaking driver, so there is no waiting for a shared shuttle and no taxi meter. You pay one fixed, transparent price agreed when you book, and your driver meets you personally at arrivals with a name board for a smooth start to your holiday.",
    "included": [
      "Meet & greet at the arrivals hall with a personalised name board",
      "Flight tracking so your pickup time adjusts automatically if your flight is early or delayed",
      "One child or baby seat free of charge on request",
      "Up to 60 minutes free waiting time after you land",
      "Complimentary bottled water in the vehicle",
      "Door-to-door drop-off at the entrance of Sugar Beach Mauritius with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Flic-en-Flac public beach and lagoon",
      "Casela Nature Parks",
      "Tamarin Bay and its dolphin-watching trips",
      "Black River Gorges National Park",
      "La Preneuse beach and Martello Tower",
      "Chamarel Seven Coloured Earths and waterfall"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Sugar Beach Mauritius?",
        "a": "The private transfer from SSR International Airport to Sugar Beach in Wolmar covers around 48 km and takes about 55 minutes in normal traffic. Your driver takes the most direct route via the motorway and central plateau, and the journey is non-stop unless you ask for a comfort break."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We provide one child or baby seat free of charge when you request it at the time of booking. Just tell us the child's age so we can fit the right type of seat. Additional seats for larger families can also be arranged in advance."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so there is nothing for you to do. If your arrival is early or delayed, your driver adjusts the pickup time to match the new landing time and will be waiting for you at arrivals. You also have up to 60 minutes of free waiting time after you land."
      },
      {
        "q": "Can I book a return or departure transfer?",
        "a": "Absolutely. You can book your return transfer from Sugar Beach back to the airport at the same time, and we recommend it so your departure is already arranged. Your driver collects you from the hotel at an agreed time to get you to the airport with plenty of margin before check-in."
      }
    ]
  },
  {
    "slug": "sofitel-so-mauritius",
    "hotelName": "Sofitel So Mauritius",
    "area": "Bel Ombre",
    "region": "South",
    "distanceKmFromAirport": 40,
    "durationMinFromAirport": 50,
    "intro": "Sofitel So Mauritius sits on the unspoilt south coast at Bel Ombre, roughly 40 km from SSR International Airport. Our pre-booked private transfer takes you door to door in about 50 minutes, with a friendly local driver who speaks English and French. You travel in a comfortable air-conditioned car at a fixed, transparent price agreed when you book, so there is no meter and no surprises on arrival. Your driver meets you inside the arrivals hall with a name board, helps with your bags and drives you straight to the hotel entrance.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Flight tracking so your pickup time adjusts automatically if your flight is delayed",
      "First child or baby seat free of charge on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at the Sofitel So Mauritius entrance with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Bel Ombre Nature Reserve and Frederica Reserve",
      "Sept Cascades (Seven Waterfalls) hiking trails near Henrietta",
      "Chamarel Seven Coloured Earth and Chamarel Waterfall",
      "Black River Gorges National Park",
      "Le Morne Brabant UNESCO World Heritage mountain",
      "Heritage Golf Club at Bel Ombre"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Sofitel So Mauritius?",
        "a": "The drive from SSR International Airport to Sofitel So Mauritius in Bel Ombre is about 40 km and takes roughly 50 minutes in normal traffic. The route runs along the south coast, so timing can vary slightly depending on conditions and time of day."
      },
      {
        "q": "How much luggage can I bring?",
        "a": "Our standard car comfortably fits two large suitcases and two cabin bags for up to three passengers. If you are travelling with extra luggage, golf clubs or a larger group, let us know when booking and we will assign a bigger vehicle at no surprise cost."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. The first child or baby seat is provided free of charge when you request it during booking. Just tell us your child's age so we can fit the correct seat, and add a note if you need more than one."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time, so your driver adjusts the pickup to your actual landing time at no extra charge. You also have up to 60 minutes of free waiting time after you clear immigration and collect your bags."
      }
    ]
  },
  {
    "slug": "heritage-le-telfair",
    "hotelName": "Heritage Le Telfair",
    "area": "Bel Ombre",
    "region": "South",
    "distanceKmFromAirport": 42,
    "durationMinFromAirport": 50,
    "intro": "Heritage Le Telfair sits on the unspoilt south coast at Bel Ombre, about a 50-minute drive from SSR International Airport along the scenic south-coast road. Belle Mare Tours runs a private, door-to-door transfer straight to the resort entrance — no shared shuttles, no waiting around. A licensed local driver who speaks English and French meets you at arrivals, helps with your bags, and drives you to the hotel at one fixed, transparent price agreed before you travel. There is no meter and no surprise surcharge, so you know the cost the moment you book.",
    "included": [
      "Meet & greet inside the arrivals hall with a personalised name board",
      "Flight tracking so your pickup time adjusts automatically if your flight is delayed",
      "One child or baby seat free of charge on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at the Heritage Le Telfair entrance with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Bel Ombre Nature Reserve and Frederica Reserve safaris",
      "Château de Bel Ombre and its colonial gardens",
      "Heritage Golf Club Bel Ombre",
      "Rochester Falls near Souillac",
      "Gris Gris cliffs and the wild southern coastline",
      "La Vanille Nature Park (giant tortoises and crocodiles)"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to Heritage Le Telfair?",
        "a": "The drive from SSR International Airport to Heritage Le Telfair in Bel Ombre is roughly 42 km and takes about 50 minutes by private car, following the south-coast road through Souillac. Travel time can vary slightly with traffic and weather."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We provide one baby or child seat free of charge on request — just tell us the child's age when you book so we fit the correct seat. Additional seats can be arranged for larger families at no extra cost."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time, so your driver adjusts the pickup to your actual landing time. There is no penalty for delays, and you get up to 60 minutes of free waiting after touchdown to clear immigration and collect your bags."
      },
      {
        "q": "Can I book a return or departure transfer as well?",
        "a": "Absolutely. Most guests book a round trip so we collect you from Heritage Le Telfair and bring you back to the airport in good time for check-in. Share your departure flight details and we'll set the pickup time for you."
      }
    ]
  },
  {
    "slug": "trou-aux-biches-beachcomber",
    "hotelName": "Trou aux Biches Beachcomber",
    "area": "Trou aux Biches",
    "region": "North",
    "distanceKmFromAirport": 60,
    "durationMinFromAirport": 70,
    "intro": "Trou aux Biches Beachcomber sits on one of the finest stretches of sand on Mauritius' north-west coast, roughly 60 km from SSR Airport. The drive north along the motorway takes about 70 minutes in normal traffic. Belle Mare Tours runs a door-to-door private transfer in a comfortable air-conditioned car with a local, English and French-speaking driver who meets you at arrivals. You pay one fixed, transparent price agreed at booking, with no meter and no surprises, and travel straight to your hotel reception. It is a calm, reliable start to your stay.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Flight tracking so your driver adjusts the pickup time if your plane is early or delayed",
      "One complimentary child or baby seat on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at Trou aux Biches Beachcomber reception, with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Trou aux Biches public beach and lagoon, ideal for swimming and snorkelling",
      "Mont Choisy Beach, a long curve of sand a short drive north",
      "Grand Baie village for restaurants, shopping and boat trips",
      "Pamplemousses Sir Seewoosagur Ramgoolam Botanical Garden",
      "Cap Malheureux and its iconic red-roofed church",
      "Catamaran cruises to the northern islands such as Gabriel and Flat Island"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to Trou aux Biches Beachcomber?",
        "a": "The drive from SSR Airport to Trou aux Biches Beachcomber is about 60 km and normally takes around 70 minutes. Travel time can vary slightly with traffic around Port Louis, and your driver takes the fastest sensible route on the day."
      },
      {
        "q": "How much luggage can the car take?",
        "a": "A standard private car comfortably fits two large suitcases plus hand luggage for up to three passengers. If you are travelling as a larger group or with extra bags, golf clubs or a baby buggy, just tell us when booking and we will assign a larger vehicle."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We provide one suitable child or baby seat free of charge on request. Please tell us your child's age when you book so we fit the right seat, and let us know if you need more than one."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so your driver adjusts the pickup time automatically if you land early or late. You also have up to 60 minutes of free waiting after touchdown, which covers immigration and baggage collection at no extra cost."
      }
    ]
  },
  {
    "slug": "canonnier-beachcomber",
    "hotelName": "Canonnier Beachcomber",
    "area": "Pointe aux Cannoniers",
    "region": "North",
    "distanceKmFromAirport": 70,
    "durationMinFromAirport": 80,
    "intro": "Canonnier Beachcomber sits on the headland of Pointe aux Cannoniers on the north coast, roughly 70 km from SSR Airport in the south-east, a drive of around 80 minutes via the motorway. We provide a pre-booked, door-to-door private transfer straight to the hotel entrance, with a local English- and French-speaking driver-guide who meets you inside arrivals. The price is fixed and agreed when you book, so there is no meter and no surprises on arrival. After a long flight, you simply step out, find your name board, and ride in comfort to your room.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Flight tracking so your pickup adjusts automatically if your flight is early or delayed",
      "One complimentary child or baby seat on request (extra seats available)",
      "Up to 60 minutes of free waiting time after your flight lands",
      "Bottled water in the vehicle for every passenger",
      "Door-to-door drop-off at the Canonnier Beachcomber reception, plus instant email confirmation"
    ],
    "nearbyAttractions": [
      "Grand Baie village, beach and waterfront restaurants",
      "La Cuvette public beach",
      "Cap Malheureux and its iconic red-roofed church",
      "Mont Choisy beach and its long stretch of sand",
      "Pereybere beach and snorkelling spots",
      "Boat trips to Île aux Cerfs and the northern islands from Grand Baie"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Canonnier Beachcomber?",
        "a": "The drive from SSR Airport to Canonnier Beachcomber in Pointe aux Cannoniers is about 70 km and normally takes around 80 minutes. Times can vary slightly with traffic around Port Louis and the time of day, but your driver takes the fastest sensible route via the motorway."
      },
      {
        "q": "How much luggage fits in the vehicle?",
        "a": "A standard saloon car comfortably takes up to 3 passengers with 3 large suitcases plus hand luggage. If you are travelling as a family or group, or have surfboards, golf bags or extra cases, just tell us when booking and we will send a larger vehicle such as an SUV or minivan."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. Your first baby or child seat is included free of charge, and we carry infant, toddler and booster options. Please tell us your children's ages when you book so the correct seat is fitted and ready in the vehicle on arrival."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so there is nothing for you to do. Your driver adjusts the pickup time automatically to match the new landing time, and you also get up to 60 minutes of free waiting after touchdown while you clear immigration and collect your bags at no extra cost."
      }
    ]
  },
  {
    "slug": "lux-grand-gaube",
    "hotelName": "LUX* Grand Gaube",
    "area": "Grand Gaube",
    "region": "North",
    "distanceKmFromAirport": 70,
    "durationMinFromAirport": 80,
    "intro": "LUX* Grand Gaube sits on the quiet northern tip of Mauritius, around 70 km from SSR International Airport, a drive of roughly 80 minutes via the motorway. Belle Mare Tours runs a door-to-door private transfer with a licensed, English- and French-speaking local driver who meets you in the arrivals hall and carries your bags to the car. You travel in a private, air-conditioned vehicle, not a shared shuttle, for one fixed and transparent price agreed when you book. There is no meter and no surprise at the end of the trip.",
    "included": [
      "Meet and greet inside the arrivals hall with a name board",
      "Flight tracking so your pickup adjusts automatically to delays or early landings",
      "First child or baby seat free on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at LUX* Grand Gaube reception",
      "Instant confirmation by email with your driver's details"
    ],
    "nearbyAttractions": [
      "Grand Gaube fishing village and waterfront",
      "Cap Malheureux and its red-roofed chapel",
      "Île d'Ambre boat and kayak trips through the mangroves",
      "Grand Baie for shopping, restaurants and nightlife",
      "Pereybere public beach",
      "Mont Choisy beach and coastal road"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to LUX* Grand Gaube?",
        "a": "The drive from SSR International Airport to LUX* Grand Gaube is about 70 km and normally takes around 80 minutes. Most of the route is on the M1/M2 motorway, with the last stretch on coastal roads through the north. Times can be a little longer during weekday rush hours."
      },
      {
        "q": "How much luggage can you carry?",
        "a": "A standard sedan comfortably takes two large suitcases plus hand luggage for two passengers. If you are travelling as a family or group, or with golf bags, surfboards or extra cases, just tell us your numbers when booking and we will send a larger vehicle such as an SUV or minivan at no surprise cost."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. The first baby or child seat is free on request. Please tell us the child's age and weight when you book so we fit the correct seat. Additional seats can be arranged for a small charge and are confirmed in your booking email."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight number, so your driver's pickup time adjusts automatically if you land early or late, with no penalty. You also get up to 60 minutes of free waiting time after touchdown to clear passport control and collect your bags, which covers most delays at arrivals."
      }
    ]
  },
  {
    "slug": "ravenala-attitude",
    "hotelName": "The Ravenala Attitude",
    "area": "Balaclava",
    "region": "North",
    "distanceKmFromAirport": 65,
    "durationMinFromAirport": 75,
    "intro": "The Ravenala Attitude sits on the calm Turtle Bay coast at Balaclava, in the north-west of Mauritius. From SSR Airport in the south-east, the drive across the island takes around 75 minutes via the motorway and Port Louis ring road. Belle Mare Tours offers a pre-booked, door-to-door private transfer in an air-conditioned car with a licensed local driver who speaks English and French. You travel for a fixed, transparent price agreed at booking, with no meter and no surprises. Your driver meets you in the arrivals hall and takes you straight to the hotel reception.",
    "included": [
      "Meet and greet inside the arrivals hall with a name board",
      "Flight tracking so your pickup adjusts automatically to early or delayed arrivals",
      "One free child or baby seat on request",
      "Up to 60 minutes of free waiting time after landing",
      "Complimentary bottled water in the vehicle",
      "Door-to-door drop-off at The Ravenala Attitude reception with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Baie aux Tortues (Turtle Bay) and Maritim beach",
      "Trou aux Biches public beach",
      "Pointe aux Piments and the Aquarium of Mauritius",
      "Grand Baie shops, restaurants and nightlife",
      "Caudan Waterfront and central Port Louis",
      "Pamplemousses Botanical Garden (SSR Garden)"
    ],
    "faq": [
      {
        "q": "How long is the transfer from the airport to The Ravenala Attitude?",
        "a": "The drive from SSR Airport to Balaclava is about 65 km and takes roughly 75 minutes in normal traffic, using the motorway and the Port Louis ring road. Times can be a little longer at peak hours around the capital."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. Your first child or baby seat is free of charge. Just tell us the child's age when you book so the driver can fit the correct seat in advance."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so your pickup time adjusts automatically to the actual landing time. You also have up to 60 minutes of free waiting after the plane lands, at no extra cost."
      },
      {
        "q": "Can I book a return transfer back to the airport?",
        "a": "Yes. You can book a one-way arrival transfer or add a departure transfer back to SSR Airport. For the return leg we agree a pickup time at the hotel that gives you comfortable time to check in for your flight."
      }
    ]
  },
  {
    "slug": "westin-turtle-bay",
    "hotelName": "The Westin Turtle Bay Resort & Spa",
    "area": "Balaclava",
    "region": "North",
    "distanceKmFromAirport": 55,
    "durationMinFromAirport": 65,
    "intro": "The Westin Turtle Bay Resort & Spa sits on the sheltered bay at Balaclava, on the northwest coast of Mauritius, about 55 km from SSR International Airport in the southeast. The drive takes roughly an hour and five minutes via the motorway past Port Louis. Belle Mare Tours runs a door-to-door private transfer with a licensed, English and French-speaking local driver. You pay a fixed, transparent price agreed at booking, with no meter and no surprises. Your driver meets you in the arrivals hall with a name board and takes you straight to the resort.",
    "included": [
      "Meet and greet in the arrivals hall with a personalised name board",
      "Flight tracking so your pickup adjusts automatically if your flight is delayed",
      "Free first child or baby seat on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water in the vehicle",
      "Door-to-door drop-off at The Westin Turtle Bay Resort & Spa with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Balaclava Ruins and the historic Bain des Dames",
      "Baie aux Tortues (Turtle Bay) marine park for snorkelling",
      "Maritim Château de Labourdonnais area and northern beaches at Trou aux Biches",
      "Port Louis Caudan Waterfront and Central Market",
      "Pamplemousses Sir Seewoosagur Ramgoolam Botanical Garden",
      "Grand Baie shopping, restaurants and nightlife"
    ],
    "faq": [
      {
        "q": "How long is the transfer to The Westin Turtle Bay Resort & Spa?",
        "a": "The drive from SSR International Airport to Balaclava is about 55 km and takes roughly an hour and five minutes by private car, mostly on the motorway past Port Louis. Travel time can vary slightly with traffic around Port Louis during peak hours."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight using your flight number, so your driver adjusts the pickup time automatically. There is no need to call or rebook. You also get up to 60 minutes of free waiting time after landing while you clear immigration and collect your bags."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. The first child or baby seat is free on request. Just tell us the age of your child when you book so we can fit the right seat. Additional seats can be arranged for larger families."
      },
      {
        "q": "Can I book a return or departure transfer back to the airport?",
        "a": "Yes. You can book a one-way transfer or a return, and we will pick you up from The Westin Turtle Bay Resort & Spa at an agreed time for your departure flight, allowing for the roughly hour-long drive back to SSR Airport."
      }
    ]
  },
  {
    "slug": "le-meridien-ile-maurice",
    "hotelName": "Le Méridien Ile Maurice",
    "area": "Pointe aux Piments",
    "region": "North",
    "distanceKmFromAirport": 62,
    "durationMinFromAirport": 75,
    "intro": "Arrive at Le Méridien Ile Maurice in Pointe aux Piments without the stress of finding a taxi. Our pre-booked private transfer takes you door to door from SSR International Airport, a drive of roughly 62 km up the west coast that usually takes about 75 minutes via the motorway through Port Louis. A friendly local driver who speaks English and French meets you in the arrivals hall with a name board, helps with your bags, and drives you straight to the hotel. You pay one fixed, transparent price agreed when you book, with no meter and no surprises on arrival.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Live flight tracking so your pickup is adjusted automatically if your flight is early or delayed",
      "First child or baby seat free of charge on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at the entrance of Le Méridien Ile Maurice with instant email confirmation of your booking"
    ],
    "nearbyAttractions": [
      "Trou aux Biches public beach and snorkelling lagoon",
      "Mauritius Aquarium at Pointe aux Piments",
      "Triolet Shivala (Maheswarnath Mandir), the island's largest Hindu temple",
      "Grand Baie shopping, restaurants and nightlife",
      "Pamplemousses (SSR) Botanical Garden",
      "Boat trips to the northern islands from Trou aux Biches"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Le Méridien Ile Maurice?",
        "a": "Pointe aux Piments is on the north-west coast, while the airport is in the south-east. The drive is about 62 km and normally takes around 75 minutes by private car via the motorway through Port Louis. Allow a little extra during Port Louis rush hour in the morning and late afternoon."
      },
      {
        "q": "How much luggage can the car take?",
        "a": "A standard car comfortably fits two passengers with two large suitcases plus cabin bags. If you are travelling as a family or group, or with golf clubs, surfboards or extra bags, just tell us when you book and we will assign a larger vehicle so everything and everyone fits in comfort."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We carry baby and child seats and the first seat is free of charge. Please let us know your child's age and the seat type you need when booking so the correct seat is fitted and ready in the car before you arrive."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time, so your driver adjusts the pickup to your actual landing time at no extra cost. You also have up to 60 minutes of free waiting after you land, which covers immigration and baggage collection, so your driver will be waiting whenever you reach the arrivals hall."
      }
    ]
  },
  {
    "slug": "victoria-beachcomber",
    "hotelName": "Victoria Beachcomber",
    "area": "Pointe aux Piments",
    "region": "North",
    "distanceKmFromAirport": 63,
    "durationMinFromAirport": 75,
    "intro": "Victoria Beachcomber sits on the calm north-west coast at Pointe aux Piments, about 63 km from SSR International Airport in the south-east. Our private door-to-door transfer takes roughly 75 minutes via the motorway past Port Louis, with no shared stops or detours. A licensed, English- and French-speaking local driver meets you at arrivals with a name board and carries your bags straight to a clean, air-conditioned car. You pay one fixed, transparent price agreed at booking, with no meter and no surprises, and travel directly to the hotel reception.",
    "included": [
      "Meet and greet inside the arrivals hall with a personalised name board",
      "Flight tracking so your driver adjusts the pickup time to any delay",
      "First child or baby seat free on request",
      "Up to 60 minutes free waiting time after landing",
      "Complimentary bottled water on board",
      "Door-to-door drop-off at Victoria Beachcomber reception",
      "Instant email confirmation with your driver and price details"
    ],
    "nearbyAttractions": [
      "Aquarium of Mauritius at Pointe aux Piments",
      "Public beach and snorkelling at Trou aux Biches",
      "Mont Choisy beach and sands",
      "Pamplemousses (SSR) Botanical Garden",
      "Port Louis Caudan Waterfront and Central Market",
      "Day trips north to Grand Baie"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Victoria Beachcomber?",
        "a": "The drive from SSR Airport to Victoria Beachcomber at Pointe aux Piments is about 63 km and takes roughly 75 minutes in normal traffic, using the motorway past Port Louis. Heavy rush-hour traffic around the capital can add 15 to 20 minutes."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. The first child or baby seat is free when you request it at booking, and we can supply infant, toddler or booster seats. Just tell us your children's ages and we will fit the correct seat before pickup."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight, so your driver adjusts the pickup time automatically to the actual landing. There is no extra charge for normal delays, and up to 60 minutes of free waiting time after you land is included while you clear immigration and collect your bags."
      },
      {
        "q": "Can I book a return or departure transfer?",
        "a": "Yes. You can book a one-way airport-to-hotel trip, a hotel-to-airport departure, or both as a round trip. For departures we set the pickup time based on your flight so you reach the airport with comfortable time to spare."
      }
    ]
  },
  {
    "slug": "radisson-blu-azuri",
    "hotelName": "Radisson Blu Azuri Resort & Spa",
    "area": "Roches Noires",
    "region": "East",
    "distanceKmFromAirport": 62,
    "durationMinFromAirport": 70,
    "intro": "Start your holiday at Radisson Blu Azuri Resort & Spa in Roches Noires the easy way, with a pre-booked private transfer from SSR International Airport. Your local English- and French-speaking driver meets you at arrivals with a name board, helps with your luggage and drives you straight to the resort, no shared shuttle or waiting around. The roughly 70-minute journey up the east coast is at a fixed, transparent price agreed when you book, so there is no meter and no surprises on arrival. Just door-to-door comfort after a long flight.",
    "included": [
      "Meet & greet at the arrivals hall with a personalised name board",
      "Flight tracking so your driver adjusts pickup to any delay or early landing",
      "Free first child or baby seat on request",
      "Up to 60 minutes of free waiting time after you land",
      "Complimentary bottled water in an air-conditioned vehicle",
      "Door-to-door drop-off at Radisson Blu Azuri Resort & Spa with instant email confirmation"
    ],
    "nearbyAttractions": [
      "Roches Noires public beach and lagoon",
      "Roches Noires sea caves (lava tunnels)",
      "Poste Lafayette beach and kitesurfing spots",
      "Bras d'Eau National Park",
      "Île d'Ambre (kayaking and mangrove trips)",
      "Grand Baie shops, restaurants and nightlife (north coast)"
    ],
    "faq": [
      {
        "q": "How long is the transfer to Radisson Blu Azuri Resort & Spa?",
        "a": "The drive from SSR International Airport to Roches Noires is about 62 km and takes around 70 minutes in a private car, depending on traffic and the time of day. Your driver takes the fastest sensible route up the east coast so you reach the resort comfortably."
      },
      {
        "q": "How much luggage can I bring?",
        "a": "A standard saloon car comfortably fits two large suitcases plus hand luggage for up to three passengers. Travelling as a family or group, or with extra bags, golf clubs or a baby buggy? Just tell us when you book and we will assign a larger vehicle at no surprise cost."
      },
      {
        "q": "Are child seats available?",
        "a": "Yes. We provide your first baby or child seat free of charge. Let us know your child's age when booking and we will fit the correct seat so your little ones travel safely to the resort."
      },
      {
        "q": "What happens if my flight is delayed?",
        "a": "We track your flight in real time, so if it lands early or late your driver adjusts the pickup automatically. You also get up to 60 minutes of free waiting time after landing, with no extra charge for normal delays."
      }
    ]
  }
];
