/**
 * Bundles every migration (in order) + the generated seed into a single
 * `supabase/setup.sql` you can paste into the Supabase SQL Editor once, on a fresh
 * project. No CLI/Docker needed. Run `npm run seed:gen` first so seed.sql is current.
 *
 * NOTE: this is the REAL-Supabase path — it does NOT include the PGlite-only auth
 * shim (tests/db/auth-shim.sql), because auth.uid()/roles are native in Supabase.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const migrationsDir = join(root, 'supabase', 'migrations');
const seedPath = join(root, 'supabase', 'seed.sql');
const outPath = join(root, 'supabase', 'setup.sql');

const migrations = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort();

const parts: string[] = [
  '-- GENERATED by scripts/build-setup-sql.ts — do not edit by hand.',
  '-- Paste this whole file into the Supabase SQL Editor on a fresh project and Run.',
  '-- Order: all migrations, then the catalogue seed.',
  'begin;',
];

for (const file of migrations) {
  parts.push(`\n-- ==================== ${file} ====================`);
  parts.push(readFileSync(join(migrationsDir, file), 'utf8').trimEnd());
}

if (existsSync(seedPath)) {
  parts.push('\n-- ==================== seed.sql (catalogue) ====================');
  parts.push(readFileSync(seedPath, 'utf8').trimEnd());
} else {
  parts.push('\n-- (seed.sql not found — run `npm run seed:gen` first to include catalogue data)');
}

// Planner data (the bookable Custom Road Trip activity) — applied after the catalogue so the operator exists.
const seedPlannerPath = join(root, 'supabase', 'seed-planner.sql');
if (existsSync(seedPlannerPath)) {
  parts.push('\n-- ==================== seed-planner.sql (Custom Road Trip) ====================');
  parts.push(readFileSync(seedPlannerPath, 'utf8').trimEnd());
}

parts.push('\ncommit;');

writeFileSync(outPath, parts.join('\n') + '\n', 'utf8');
console.log(
  `Wrote ${outPath} (${migrations.length} migrations${existsSync(seedPath) ? ' + seed' : ''}).`,
);
