/**
 * Bundles every migration (in order) + the generated seed into a single
 * `supabase/setup.sql` you can paste into the Supabase SQL Editor once, on a fresh
 * project. No CLI/Docker needed. Run `npm run seed:gen` first so seed.sql is current.
 *
 * NOTE: this is the REAL-Supabase path — it does NOT include the PGlite-only auth
 * shim (tests/db/auth-shim.sql), because auth.uid()/roles are native in Supabase.
 *
 * `buildSetupSql()` is a PURE function (no writes) so tests can assert the committed
 * supabase/setup.sql is in sync with the migrations — see tests/integration/setup-sql-parity.test.ts.
 * Running this file as a script writes the bundle to disk.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/** Builds the full setup.sql bundle text from the migrations + seed files. Pure — returns the string. */
export function buildSetupSql(root: string = process.cwd()): string {
  const migrationsDir = join(root, 'supabase', 'migrations');
  const seedPath = join(root, 'supabase', 'seed.sql');
  const seedPlannerPath = join(root, 'supabase', 'seed-planner.sql');

  const migrations = readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .sort();

  const parts: string[] = [
    '-- GENERATED by scripts/build-setup-sql.ts — do not edit by hand.',
    '-- Paste this whole file into the Supabase SQL Editor on a fresh project and Run.',
    '-- Order: all migrations, then the catalogue seed.',
    'begin;',
  ];

  for (const file of migrations) {
    parts.push(`\n-- ==================== ${file} ====================`);
    parts.push(readFileSync(join(migrationsDir, file), 'utf8').trimEnd());
  }

  if (existsSync(seedPath)) {
    parts.push('\n-- ==================== seed.sql (catalogue) ====================');
    parts.push(readFileSync(seedPath, 'utf8').trimEnd());
  } else {
    parts.push('\n-- (seed.sql not found — run `npm run seed:gen` first to include catalogue data)');
  }

  // Planner data (the bookable Custom Road Trip activity) — applied after the catalogue so the operator exists.
  if (existsSync(seedPlannerPath)) {
    parts.push('\n-- ==================== seed-planner.sql (Custom Road Trip) ====================');
    parts.push(readFileSync(seedPlannerPath, 'utf8').trimEnd());
  }

  parts.push('\ncommit;');

  return parts.join('\n') + '\n';
}

/** Count of migration files bundled — for the CLI log line. */
function migrationCount(root: string = process.cwd()): number {
  return readdirSync(join(root, 'supabase', 'migrations')).filter((f) => f.endsWith('.sql')).length;
}

// CLI entry: write the bundle to supabase/setup.sql.
if (import.meta.url === `file://${process.argv[1]}` || process.argv[1]?.endsWith('build-setup-sql.ts')) {
  const root = process.cwd();
  const outPath = join(root, 'supabase', 'setup.sql');
  writeFileSync(outPath, buildSetupSql(root), 'utf8');
  const seedExists = existsSync(join(root, 'supabase', 'seed.sql'));
  console.log(`Wrote ${outPath} (${migrationCount(root)} migrations${seedExists ? ' + seed' : ''}).`);
}
