import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { posts } from '@/lib/content/blog';
import { BLOG_HERO } from '@/lib/content/blog-images';
import { articleJsonLd, attractionJsonLd } from '@/lib/seo/jsonld';

/**
 * Blog hero photos. The 40 seed posts ship no image of their own, which left /blog a wall of text-only
 * cards and every social share falling back to the site-wide OG image. BLOG_HERO (generated by
 * scripts/fetch-blog-photos.ts alongside the files in public/blog) fills that gap.
 *
 * These guard the two ways it silently rots: a map entry whose file isn't actually on disk (broken
 * image, and `next build` won't catch it because the path is a plain string), and a hero that stops
 * reaching the post.
 */
describe('blog hero images', () => {
  it('every seed post has a hero', () => {
    const missing = posts.filter((p) => !p.heroImageUrl).map((p) => p.slug);
    expect(missing, `posts with no hero: ${missing.join(', ')}`).toEqual([]);
  });

  it('every mapped hero file actually exists in public/blog', () => {
    const absent = Object.entries(BLOG_HERO)
      .filter(([, url]) => !existsSync(join(process.cwd(), 'public', url.replace(/^\//, ''))))
      .map(([slug]) => slug);
    expect(absent, `mapped but missing on disk: ${absent.join(', ')}`).toEqual([]);
  });

  it('heroes are site-relative webp under /blog/ (served as a Pages static asset)', () => {
    for (const [slug, url] of Object.entries(BLOG_HERO)) {
      expect(url, slug).toMatch(/^\/blog\/[a-z0-9-]+\.webp$/);
    }
  });
});

/**
 * REGRESSION: schema.org/Google ignore a RELATIVE image in structured data. The blog heroes are
 * site-relative ('/blog/x.webp'), so the moment they were wired up, BlogPosting started emitting an
 * image Google would drop — costing the article its rich-result thumbnail, silently. `og:image` was
 * fine only because Next's metadata layer absolutizes it for us; hand-built JSON-LD gets no such help.
 */
describe('JSON-LD images are absolute', () => {
  const article = (image: string | null) =>
    articleJsonLd({
      title: 'T',
      description: 'D',
      path: '/blog/x',
      datePublished: '2026-01-01',
      image,
    });

  it('absolutizes a site-relative article image', () => {
    expect(article('/blog/x.webp').image).toMatch(/^https?:\/\/.+\/blog\/x\.webp$/);
  });

  it('leaves an already-absolute image alone', () => {
    const url = 'https://cdn.example.com/x.jpg';
    expect(article(url).image).toBe(url);
  });

  it('omits image entirely when there is none (never emits null)', () => {
    expect(article(null)).not.toHaveProperty('image');
  });

  it('absolutizes the attraction image too (same trap)', () => {
    const json = attractionJsonLd(
      {
        id: 'p1',
        name: 'Place',
        category: 'Beach',
        region: 'East',
        lat: -20.2,
        lng: 57.7,
        durationMin: 60,
        closesAt: null,
        blurb: null,
        imageUrl: null,
      } as unknown as Parameters<typeof attractionJsonLd>[0],
      { path: '/attractions/p1', image: '/activities/x.jpg' },
    );
    expect(json.image).toMatch(/^https?:\/\/.+\/activities\/x\.jpg$/);
  });
});
